[tool.poetry]
name = "abc-gpt"
version = "0.1.0"
description = ""
authors = ["Sergio N. <serhii@journey.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
torch = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
